theme: minima
title: Zweisprachiges Online-WÃ¶rterbuch der Phrasem-Konstruktionen
author: caracumba
email: kroelebor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
# social links
github_username:  caracumba

show_excerpts: true # set to false to remove excerpts on the homepage
